// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: ebf_final_va

#ifndef _EBF_FINAL_VA_UI_H
#define _EBF_FINAL_VA_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////
#include "ui_ChargingScreen.h"
#include "ui_MainScreen.h"
#include "ui_TherapyScreen.h"
#include "ui_FilterScreen.h"
#include "ui_SettingScreen.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_battery_charging_png);   // assets/battery charging.png
LV_IMG_DECLARE( ui_img_2022142161);   // assets/triangle-up.png
LV_IMG_DECLARE( ui_img_732690875);   // assets/triangle-left.png
LV_IMG_DECLARE( ui_img_33364130);   // assets/triangle-down.png
LV_IMG_DECLARE( ui_img_1713356312);   // assets/tick-icon.png
LV_IMG_DECLARE( ui_img_548664401);   // assets/plus-icon.png
LV_IMG_DECLARE( ui_img_1546845897);   // assets/cross-icon.png
LV_IMG_DECLARE( ui_img_1759250347);   // assets/minus-icon.png
LV_IMG_DECLARE( ui_img_719203222);   // assets/triangle-right.png
LV_IMG_DECLARE( ui_img_battery_low_png);   // assets/battery low.png
LV_IMG_DECLARE( ui_img_battery_discharge_png);   // assets/battery discharge.png
LV_IMG_DECLARE( ui_img_battery_full_png);   // assets/battery full.png
LV_IMG_DECLARE( ui_img_bluetooth_icon_png);   // assets/bluetooth icon.png

// FONTS
LV_FONT_DECLARE( ui_font_Number_Medium);
LV_FONT_DECLARE( ui_font_Number_Small);
LV_FONT_DECLARE( ui_font_Number);
LV_FONT_DECLARE( ui_font_Number_SMedium);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
