// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: ebf_final_va

#include "ui.h"

lv_obj_t *ui_ChargingScreen = NULL;
// event funtions

// build funtions

void ui_ChargingScreen_screen_init(void)
{
ui_ChargingScreen = lv_obj_create(NULL);
lv_obj_remove_flag( ui_ChargingScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_style_bg_color(ui_ChargingScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ChargingScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( ui_ChargingScreen, &ui_img_battery_charging_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_image_recolor(ui_ChargingScreen, lv_color_hex(0x4040FF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_recolor_opa(ui_ChargingScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_ChargingScreen_screen_destroy(void)
{
   if (ui_ChargingScreen) lv_obj_del(ui_ChargingScreen);

// NULL screen variables
ui_ChargingScreen= NULL;

}
