// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: ebf_final_va

#ifndef UI_CHARGINGSCREEN_H
#define UI_CHARGINGSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif


// SCREEN: ui_ChargingScreen
extern void ui_ChargingScreen_screen_init(void);
extern void ui_ChargingScreen_screen_destroy(void);
extern lv_obj_t *ui_ChargingScreen;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

