// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: ebf_final_va

#ifndef UI_FILTERSCREEN_H
#define UI_FILTERSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif


// SCREEN: ui_FilterScreen
extern void ui_FilterScreen_screen_init(void);
extern void ui_FilterScreen_screen_destroy(void);
extern lv_obj_t *ui_FilterScreen;
extern lv_obj_t *ui_Header3;
extern lv_obj_t *ui_Header_Battery3;
extern lv_obj_t *ui_Batt_Icon3;
extern lv_obj_t *ui_BT_Icon3;
extern lv_obj_t *ui_Roller_Topic3;
extern lv_obj_t *ui_Freq_Text3;
extern lv_obj_t *ui_Freq_Value3;
extern lv_obj_t *ui_Button_Panel3;
extern lv_obj_t *ui_ButtonLeft3;
extern lv_obj_t *ui_ButtonMidLeft3;
extern lv_obj_t *ui_ButtonMidRight3;
extern lv_obj_t *ui_ButtonRight3;
extern lv_obj_t *ui_Strength_Value2;
extern lv_obj_t *ui_Text12;
extern lv_obj_t *ui_Extra_Value6;
extern lv_obj_t *ui_Bar1;
extern lv_obj_t *ui_Text7;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

