// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: ebf_final_va

#include "ui.h"

lv_obj_t *ui_FilterScreen = NULL;lv_obj_t *ui_Header3 = NULL;lv_obj_t *ui_Header_Battery3 = NULL;lv_obj_t *ui_Batt_Icon3 = NULL;lv_obj_t *ui_BT_Icon3 = NULL;lv_obj_t *ui_Roller_Topic3 = NULL;lv_obj_t *ui_Freq_Text3 = NULL;lv_obj_t *ui_Freq_Value3 = NULL;lv_obj_t *ui_Button_Panel3 = NULL;lv_obj_t *ui_ButtonLeft3 = NULL;lv_obj_t *ui_ButtonMidLeft3 = NULL;lv_obj_t *ui_ButtonMidRight3 = NULL;lv_obj_t *ui_ButtonRight3 = NULL;lv_obj_t *ui_Strength_Value2 = NULL;lv_obj_t *ui_Text12 = NULL;lv_obj_t *ui_Extra_Value6 = NULL;lv_obj_t *ui_Bar1 = NULL;lv_obj_t *ui_Text7 = NULL;
// event funtions

// build funtions

void ui_FilterScreen_screen_init(void)
{
ui_FilterScreen = lv_obj_create(NULL);
lv_obj_remove_flag( ui_FilterScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_style_bg_color(ui_FilterScreen, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_FilterScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_FilterScreen, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT );

ui_Header3 = lv_obj_create(ui_FilterScreen);
lv_obj_set_height( ui_Header3, 50);
lv_obj_set_width( ui_Header3, lv_pct(100));
lv_obj_set_align( ui_Header3, LV_ALIGN_TOP_MID );
lv_obj_remove_flag( ui_Header3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Header3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Header3, lv_color_hex(0x14191E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Header3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Header3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Header_Battery3 = lv_label_create(ui_Header3);
lv_obj_set_width( ui_Header_Battery3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Header_Battery3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Header_Battery3, 0 );
lv_obj_set_y( ui_Header_Battery3, 6 );
lv_obj_set_align( ui_Header_Battery3, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Header_Battery3,"80%");
lv_obj_remove_flag( ui_Header_Battery3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_Header_Battery3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Header_Battery3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Batt_Icon3 = lv_image_create(ui_Header3);
lv_image_set_src(ui_Batt_Icon3, &ui_img_battery_low_png);
lv_obj_set_width( ui_Batt_Icon3, 30);
lv_obj_set_height( ui_Batt_Icon3, 20);
lv_obj_set_x( ui_Batt_Icon3, 90 );
lv_obj_set_y( ui_Batt_Icon3, -8 );
lv_obj_set_align( ui_Batt_Icon3, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Batt_Icon3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_image_set_inner_align( ui_Batt_Icon3, LV_IMAGE_ALIGN_TILE );
lv_obj_set_style_bg_image_src( ui_Batt_Icon3, &ui_img_battery_low_png, LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_bg_image_opa(ui_Batt_Icon3, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_bg_image_src( ui_Batt_Icon3, &ui_img_battery_discharge_png, LV_PART_MAIN | LV_STATE_USER_2 );
lv_obj_set_style_bg_image_opa(ui_Batt_Icon3, 255, LV_PART_MAIN| LV_STATE_USER_2);
lv_obj_set_style_bg_image_src( ui_Batt_Icon3, &ui_img_battery_full_png, LV_PART_MAIN | LV_STATE_USER_3 );
lv_obj_set_style_bg_image_opa(ui_Batt_Icon3, 255, LV_PART_MAIN| LV_STATE_USER_3);
lv_obj_set_style_bg_image_src( ui_Batt_Icon3, &ui_img_battery_charging_png, LV_PART_MAIN | LV_STATE_USER_4 );
lv_obj_set_style_bg_image_opa(ui_Batt_Icon3, 255, LV_PART_MAIN| LV_STATE_USER_4);

ui_BT_Icon3 = lv_image_create(ui_Header3);
lv_image_set_src(ui_BT_Icon3, &ui_img_bluetooth_icon_png);
lv_obj_set_width( ui_BT_Icon3, 30);
lv_obj_set_height( ui_BT_Icon3, 30);
lv_obj_set_x( ui_BT_Icon3, 50 );
lv_obj_set_y( ui_BT_Icon3, -1 );
lv_obj_set_align( ui_BT_Icon3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BT_Icon3, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_remove_flag( ui_BT_Icon3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_image_set_inner_align( ui_BT_Icon3, LV_IMAGE_ALIGN_TILE );

ui_Roller_Topic3 = lv_roller_create(ui_Header3);
lv_roller_set_options( ui_Roller_Topic3, "Settings\nStrength\nFreq Cycle\nFrequency\nIntensity\nInterval Gap\nFilter\nModulate", LV_ROLLER_MODE_INFINITE );
lv_roller_set_selected( ui_Roller_Topic3, 1, LV_ANIM_OFF);
lv_obj_set_height( ui_Roller_Topic3, 55);
lv_obj_set_width( ui_Roller_Topic3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_Roller_Topic3, -60 );
lv_obj_set_y( ui_Roller_Topic3, 0 );
lv_obj_set_align( ui_Roller_Topic3, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Roller_Topic3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_obj_set_style_text_color(ui_Roller_Topic3, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Roller_Topic3, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Roller_Topic3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Roller_Topic3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Roller_Topic3, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Roller_Topic3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Roller_Topic3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Roller_Topic3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Roller_Topic3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_Roller_Topic3, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Roller_Topic3, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Roller_Topic3, LV_TEXT_ALIGN_CENTER, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Roller_Topic3, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Roller_Topic3, 0, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_Freq_Text3 = lv_label_create(ui_FilterScreen);
lv_obj_set_width( ui_Freq_Text3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Freq_Text3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Freq_Text3, -200 );
lv_obj_set_y( ui_Freq_Text3, 89 );
lv_obj_set_align( ui_Freq_Text3, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Freq_Text3,"Freq");
lv_obj_remove_flag( ui_Freq_Text3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_Freq_Text3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Freq_Text3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Freq_Value3 = lv_label_create(ui_FilterScreen);
lv_obj_set_width( ui_Freq_Value3, 61);
lv_obj_set_height( ui_Freq_Value3, 25);
lv_obj_set_x( ui_Freq_Value3, -82 );
lv_obj_set_y( ui_Freq_Value3, 112 );
lv_obj_set_align( ui_Freq_Value3, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_Freq_Value3,LV_LABEL_LONG_CLIP);
lv_label_set_text(ui_Freq_Value3,"888Hz");
lv_obj_remove_flag( ui_Freq_Value3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_Freq_Value3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Freq_Value3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Freq_Value3, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Freq_Value3, &ui_font_Number_Small, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button_Panel3 = lv_obj_create(ui_FilterScreen);
lv_obj_set_width( ui_Button_Panel3, 240);
lv_obj_set_height( ui_Button_Panel3, 40);
lv_obj_set_x( ui_Button_Panel3, 0 );
lv_obj_set_y( ui_Button_Panel3, 140 );
lv_obj_set_align( ui_Button_Panel3, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Button_Panel3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(ui_Button_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button_Panel3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Button_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Button_Panel3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonLeft3 = lv_button_create(ui_Button_Panel3);
lv_obj_set_width( ui_ButtonLeft3, lv_pct(25));
lv_obj_set_height( ui_ButtonLeft3, lv_pct(300));
lv_obj_set_y( ui_ButtonLeft3, 0 );
lv_obj_set_x( ui_ButtonLeft3, lv_pct(-44) );
lv_obj_set_align( ui_ButtonLeft3, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_ButtonLeft3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_image_src( ui_ButtonLeft3, &ui_img_2022142161, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_image_recolor(ui_ButtonLeft3, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonLeft3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_ButtonLeft3, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_ButtonLeft3, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_ButtonLeft3, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_ButtonLeft3, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_x(ui_ButtonLeft3, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_y(ui_ButtonLeft3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( ui_ButtonLeft3, &ui_img_2022142161, LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_bg_image_recolor(ui_ButtonLeft3, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonLeft3, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_bg_image_src( ui_ButtonLeft3, &ui_img_732690875, LV_PART_MAIN | LV_STATE_USER_2 );
lv_obj_set_style_bg_image_recolor(ui_ButtonLeft3, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_2);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonLeft3, 255, LV_PART_MAIN| LV_STATE_USER_2);

ui_ButtonMidLeft3 = lv_button_create(ui_Button_Panel3);
lv_obj_set_width( ui_ButtonMidLeft3, lv_pct(25));
lv_obj_set_height( ui_ButtonMidLeft3, lv_pct(300));
lv_obj_set_y( ui_ButtonMidLeft3, 0 );
lv_obj_set_x( ui_ButtonMidLeft3, lv_pct(-15) );
lv_obj_set_align( ui_ButtonMidLeft3, LV_ALIGN_CENTER );
lv_obj_add_state( ui_ButtonMidLeft3, LV_STATE_USER_1 );     /// States
lv_obj_remove_flag( ui_ButtonMidLeft3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_image_src( ui_ButtonMidLeft3, &ui_img_2022142161, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_image_recolor(ui_ButtonMidLeft3, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonMidLeft3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_ButtonMidLeft3, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_ButtonMidLeft3, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_ButtonMidLeft3, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_ButtonMidLeft3, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_x(ui_ButtonMidLeft3, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_y(ui_ButtonMidLeft3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( ui_ButtonMidLeft3, &ui_img_33364130, LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_bg_image_recolor(ui_ButtonMidLeft3, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonMidLeft3, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_bg_image_src( ui_ButtonMidLeft3, &ui_img_732690875, LV_PART_MAIN | LV_STATE_USER_2 );
lv_obj_set_style_bg_image_recolor(ui_ButtonMidLeft3, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_2);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonMidLeft3, 255, LV_PART_MAIN| LV_STATE_USER_2);

ui_ButtonMidRight3 = lv_button_create(ui_Button_Panel3);
lv_obj_set_width( ui_ButtonMidRight3, lv_pct(25));
lv_obj_set_height( ui_ButtonMidRight3, lv_pct(300));
lv_obj_set_y( ui_ButtonMidRight3, 0 );
lv_obj_set_x( ui_ButtonMidRight3, lv_pct(15) );
lv_obj_set_align( ui_ButtonMidRight3, LV_ALIGN_CENTER );
lv_obj_add_state( ui_ButtonMidRight3, LV_STATE_USER_2 );     /// States
lv_obj_remove_flag( ui_ButtonMidRight3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_image_src( ui_ButtonMidRight3, &ui_img_2022142161, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_image_recolor(ui_ButtonMidRight3, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonMidRight3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_ButtonMidRight3, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_ButtonMidRight3, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_ButtonMidRight3, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_ButtonMidRight3, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_x(ui_ButtonMidRight3, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_y(ui_ButtonMidRight3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( ui_ButtonMidRight3, &ui_img_1713356312, LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_bg_image_recolor(ui_ButtonMidRight3, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonMidRight3, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_bg_image_src( ui_ButtonMidRight3, &ui_img_548664401, LV_PART_MAIN | LV_STATE_USER_2 );
lv_obj_set_style_bg_image_recolor(ui_ButtonMidRight3, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_2);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonMidRight3, 255, LV_PART_MAIN| LV_STATE_USER_2);
lv_obj_set_style_bg_image_src( ui_ButtonMidRight3, &ui_img_732690875, LV_PART_MAIN | LV_STATE_USER_3 );
lv_obj_set_style_bg_image_recolor(ui_ButtonMidRight3, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_3);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonMidRight3, 255, LV_PART_MAIN| LV_STATE_USER_3);
lv_obj_set_style_bg_image_src( ui_ButtonMidRight3, &ui_img_732690875, LV_PART_MAIN | LV_STATE_USER_4 );
lv_obj_set_style_bg_image_recolor(ui_ButtonMidRight3, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_4);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonMidRight3, 255, LV_PART_MAIN| LV_STATE_USER_4);

ui_ButtonRight3 = lv_button_create(ui_Button_Panel3);
lv_obj_set_width( ui_ButtonRight3, lv_pct(25));
lv_obj_set_height( ui_ButtonRight3, lv_pct(300));
lv_obj_set_y( ui_ButtonRight3, 0 );
lv_obj_set_x( ui_ButtonRight3, lv_pct(44) );
lv_obj_set_align( ui_ButtonRight3, LV_ALIGN_CENTER );
lv_obj_add_state( ui_ButtonRight3, LV_STATE_USER_2 );     /// States
lv_obj_remove_flag( ui_ButtonRight3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_image_src( ui_ButtonRight3, &ui_img_2022142161, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_image_recolor(ui_ButtonRight3, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonRight3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_ButtonRight3, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_ButtonRight3, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_ButtonRight3, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_ButtonRight3, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_x(ui_ButtonRight3, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_y(ui_ButtonRight3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( ui_ButtonRight3, &ui_img_1546845897, LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_bg_image_recolor(ui_ButtonRight3, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonRight3, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_bg_image_src( ui_ButtonRight3, &ui_img_1759250347, LV_PART_MAIN | LV_STATE_USER_2 );
lv_obj_set_style_bg_image_recolor(ui_ButtonRight3, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_2);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonRight3, 255, LV_PART_MAIN| LV_STATE_USER_2);
lv_obj_set_style_bg_image_src( ui_ButtonRight3, &ui_img_732690875, LV_PART_MAIN | LV_STATE_USER_3 );
lv_obj_set_style_bg_image_recolor(ui_ButtonRight3, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_3);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonRight3, 255, LV_PART_MAIN| LV_STATE_USER_3);
lv_obj_set_style_bg_image_src( ui_ButtonRight3, &ui_img_719203222, LV_PART_MAIN | LV_STATE_USER_4 );
lv_obj_set_style_bg_image_recolor(ui_ButtonRight3, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_4);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonRight3, 255, LV_PART_MAIN| LV_STATE_USER_4);

ui_Strength_Value2 = lv_label_create(ui_FilterScreen);
lv_obj_set_width( ui_Strength_Value2, 77);
lv_obj_set_height( ui_Strength_Value2, 25);
lv_obj_set_x( ui_Strength_Value2, 2 );
lv_obj_set_y( ui_Strength_Value2, -133 );
lv_obj_set_align( ui_Strength_Value2, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_Strength_Value2,LV_LABEL_LONG_CLIP);
lv_label_set_text(ui_Strength_Value2,"11");
lv_obj_remove_flag( ui_Strength_Value2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_Strength_Value2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Strength_Value2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Strength_Value2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Strength_Value2, &ui_font_Number_SMedium, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Text12 = lv_label_create(ui_FilterScreen);
lv_obj_set_width( ui_Text12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Text12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Text12, -176 );
lv_obj_set_y( ui_Text12, 21 );
lv_obj_set_align( ui_Text12, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Text12,"Time \nElapsed");
lv_obj_remove_flag( ui_Text12, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_Text12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Text12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Extra_Value6 = lv_label_create(ui_FilterScreen);
lv_obj_set_width( ui_Extra_Value6, 55);
lv_obj_set_height( ui_Extra_Value6, 22);
lv_obj_set_x( ui_Extra_Value6, -177 );
lv_obj_set_y( ui_Extra_Value6, 51 );
lv_obj_set_align( ui_Extra_Value6, LV_ALIGN_RIGHT_MID );
lv_label_set_long_mode(ui_Extra_Value6,LV_LABEL_LONG_CLIP);
lv_label_set_text(ui_Extra_Value6,"0s");
lv_obj_remove_flag( ui_Extra_Value6, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_Extra_Value6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Extra_Value6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Extra_Value6, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Extra_Value6, &ui_font_Number_Small, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Bar1 = lv_bar_create(ui_FilterScreen);
lv_bar_set_value(ui_Bar1,100,LV_ANIM_OFF);
lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Bar1, 150);
lv_obj_set_height( ui_Bar1, 10);
lv_obj_set_x( ui_Bar1, 0 );
lv_obj_set_y( ui_Bar1, -39 );
lv_obj_set_align( ui_Bar1, LV_ALIGN_CENTER );

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_Bar1,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_Bar1, lv_obj_get_style_pad_right(ui_Bar1,LV_PART_MAIN) + 1, LV_PART_MAIN );
ui_Text7 = lv_label_create(ui_FilterScreen);
lv_obj_set_width( ui_Text7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Text7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Text7, -47 );
lv_obj_set_y( ui_Text7, -21 );
lv_obj_set_align( ui_Text7, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Text7,"Filter ON");
lv_obj_remove_flag( ui_Text7, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_Text7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Text7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_FilterScreen_screen_destroy(void)
{
   if (ui_FilterScreen) lv_obj_del(ui_FilterScreen);

// NULL screen variables
ui_FilterScreen= NULL;
ui_Header3= NULL;
ui_Header_Battery3= NULL;
ui_Batt_Icon3= NULL;
ui_BT_Icon3= NULL;
ui_Roller_Topic3= NULL;
ui_Freq_Text3= NULL;
ui_Freq_Value3= NULL;
ui_Button_Panel3= NULL;
ui_ButtonLeft3= NULL;
ui_ButtonMidLeft3= NULL;
ui_ButtonMidRight3= NULL;
ui_ButtonRight3= NULL;
ui_Strength_Value2= NULL;
ui_Text12= NULL;
ui_Extra_Value6= NULL;
ui_Bar1= NULL;
ui_Text7= NULL;

}
