// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: ebf_final_va

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif


// SCREEN: ui_MainScreen
extern void ui_MainScreen_screen_init(void);
extern void ui_MainScreen_screen_destroy(void);
extern lv_obj_t *ui_MainScreen;
extern lv_obj_t *ui_Arc_Group1;
extern void ui_event_Arc1( lv_event_t * e);
extern lv_obj_t *ui_Arc1;
extern void ui_event_Ring1( lv_event_t * e);
extern lv_obj_t *ui_Ring1;
extern lv_obj_t *ui_Value_Num_Bg1;
extern lv_obj_t *ui_Label_Value1;
extern lv_obj_t *ui_Value_Bg1;
extern lv_obj_t *ui_Freq_Text1;
extern lv_obj_t *ui_Freq_Value1;
extern lv_obj_t *ui_Usage_Text1;
extern lv_obj_t *ui_Usage_Value1;
extern lv_obj_t *ui_Button_Panel1;
extern lv_obj_t *ui_ButtonLeft1;
extern lv_obj_t *ui_ButtonMidLeft1;
extern lv_obj_t *ui_ButtonMidRight1;
extern lv_obj_t *ui_ButtonRight1;
extern lv_obj_t *ui_Header1;
extern lv_obj_t *ui_Header_Battery1;
extern lv_obj_t *ui_Roller_Topic1;
extern lv_obj_t *ui_Batt_Icon1;
extern lv_obj_t *ui_BT_Icon1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

