// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: ebf_final_va

#include "ui.h"

lv_obj_t *ui_MainScreen = NULL;lv_obj_t *ui_Arc_Group1 = NULL;lv_obj_t *ui_Arc1 = NULL;lv_obj_t *ui_Ring1 = NULL;lv_obj_t *ui_Value_Num_Bg1 = NULL;lv_obj_t *ui_Label_Value1 = NULL;lv_obj_t *ui_Value_Bg1 = NULL;lv_obj_t *ui_Freq_Text1 = NULL;lv_obj_t *ui_Freq_Value1 = NULL;lv_obj_t *ui_Usage_Text1 = NULL;lv_obj_t *ui_Usage_Value1 = NULL;lv_obj_t *ui_Button_Panel1 = NULL;lv_obj_t *ui_ButtonLeft1 = NULL;lv_obj_t *ui_ButtonMidLeft1 = NULL;lv_obj_t *ui_ButtonMidRight1 = NULL;lv_obj_t *ui_ButtonRight1 = NULL;lv_obj_t *ui_Header1 = NULL;lv_obj_t *ui_Header_Battery1 = NULL;lv_obj_t *ui_Roller_Topic1 = NULL;lv_obj_t *ui_Batt_Icon1 = NULL;lv_obj_t *ui_BT_Icon1 = NULL;
// event funtions
void ui_event_Arc1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_arc_set_text_value( ui_Label_Value1, target, "", "°");
}
}

void ui_event_Ring1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_arc_set_text_value( ui_Label_Value1, target, "", "°");
}
}

// build funtions

void ui_MainScreen_screen_init(void)
{
ui_MainScreen = lv_obj_create(NULL);
lv_obj_remove_flag( ui_MainScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_MainScreen, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT );

ui_Arc_Group1 = lv_obj_create(ui_MainScreen);
lv_obj_set_width( ui_Arc_Group1, 220);
lv_obj_set_height( ui_Arc_Group1, 240);
lv_obj_set_align( ui_Arc_Group1, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Arc_Group1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(ui_Arc_Group1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Arc_Group1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Arc_Group1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Arc1 = lv_arc_create(ui_Arc_Group1);
lv_obj_set_width( ui_Arc1, 200);
lv_obj_set_height( ui_Arc1, 200);
lv_obj_set_align( ui_Arc1, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Arc1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_arc_set_value(ui_Arc1, 40);
lv_obj_set_style_radius(ui_Arc1, 350, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Arc1, lv_color_hex(0x1E232D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Arc1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Arc1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Arc1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Arc1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Arc1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0x0F1215), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Arc1, 15, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0x36B9F6), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Arc1, 15, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Arc1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Arc1, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Ring1 = lv_arc_create(ui_Arc_Group1);
lv_obj_set_width( ui_Ring1, 200);
lv_obj_set_height( ui_Ring1, 200);
lv_obj_set_align( ui_Ring1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Ring1, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_remove_flag( ui_Ring1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_arc_set_range(ui_Ring1, 0,1);
lv_arc_set_value(ui_Ring1, 1);
lv_arc_set_bg_angles(ui_Ring1,0,360);
lv_obj_set_style_radius(ui_Ring1, 350, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Ring1, lv_color_hex(0x1E232D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Ring1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Ring1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Ring1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Ring1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Ring1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_Ring1, lv_color_hex(0x0F1215), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Ring1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Ring1, 15, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_Ring1, lv_color_hex(0x36B9F6), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Ring1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Ring1, 15, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Ring1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Ring1, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Value_Num_Bg1 = lv_obj_create(ui_Arc_Group1);
lv_obj_set_width( ui_Value_Num_Bg1, 120);
lv_obj_set_height( ui_Value_Num_Bg1, 120);
lv_obj_set_align( ui_Value_Num_Bg1, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Value_Num_Bg1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_Value_Num_Bg1, 200, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Value_Num_Bg1, lv_color_hex(0x0C191E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Value_Num_Bg1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Value_Num_Bg1, lv_color_hex(0x191C26), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_Value_Num_Bg1, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Value_Num_Bg1, lv_color_hex(0x5A646E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Value_Num_Bg1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Value1 = lv_label_create(ui_Value_Num_Bg1);
lv_obj_set_width( ui_Label_Value1, 88);
lv_obj_set_height( ui_Label_Value1, 50);
lv_obj_set_x( ui_Label_Value1, 5 );
lv_obj_set_y( ui_Label_Value1, 0 );
lv_obj_set_align( ui_Label_Value1, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_Label_Value1,LV_LABEL_LONG_CLIP);
lv_label_set_text(ui_Label_Value1,"888");
lv_obj_remove_flag( ui_Label_Value1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_Label_Value1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Value1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_Value1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Value1, &ui_font_Number, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Value_Bg1 = lv_obj_create(ui_Arc_Group1);
lv_obj_set_width( ui_Value_Bg1, 150);
lv_obj_set_height( ui_Value_Bg1, 150);
lv_obj_set_align( ui_Value_Bg1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Value_Bg1, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_remove_flag( ui_Value_Bg1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_Value_Bg1, 280, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Value_Bg1, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Value_Bg1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Value_Bg1, lv_color_hex(0x3C414B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_Value_Bg1, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Value_Bg1, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Value_Bg1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Value_Bg1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Value_Bg1, lv_color_hex(0x050A0F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Value_Bg1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_Value_Bg1, 80, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Value_Bg1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_x(ui_Value_Bg1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_y(ui_Value_Bg1, 30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Freq_Text1 = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_Freq_Text1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Freq_Text1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Freq_Text1, -200 );
lv_obj_set_y( ui_Freq_Text1, 89 );
lv_obj_set_align( ui_Freq_Text1, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Freq_Text1,"Freq");
lv_obj_remove_flag( ui_Freq_Text1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_Freq_Text1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Freq_Text1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Freq_Value1 = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_Freq_Value1, 77);
lv_obj_set_height( ui_Freq_Value1, 25);
lv_obj_set_x( ui_Freq_Value1, -72 );
lv_obj_set_y( ui_Freq_Value1, 112 );
lv_obj_set_align( ui_Freq_Value1, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_Freq_Value1,LV_LABEL_LONG_CLIP);
lv_label_set_text(ui_Freq_Value1,"888Hz");
lv_obj_remove_flag( ui_Freq_Value1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_Freq_Value1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Freq_Value1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Freq_Value1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Freq_Value1, &ui_font_Number_Small, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Usage_Text1 = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_Usage_Text1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Usage_Text1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Usage_Text1, -188 );
lv_obj_set_y( ui_Usage_Text1, 89 );
lv_obj_set_align( ui_Usage_Text1, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Usage_Text1,"Usage:");
lv_obj_add_flag( ui_Usage_Text1, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_remove_flag( ui_Usage_Text1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_Usage_Text1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Usage_Text1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Usage_Value1 = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_Usage_Value1, 77);
lv_obj_set_height( ui_Usage_Value1, 25);
lv_obj_set_x( ui_Usage_Value1, -72 );
lv_obj_set_y( ui_Usage_Value1, 112 );
lv_obj_set_align( ui_Usage_Value1, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_Usage_Value1,LV_LABEL_LONG_CLIP);
lv_label_set_text(ui_Usage_Value1,"888H88m");
lv_obj_add_flag( ui_Usage_Value1, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_remove_flag( ui_Usage_Value1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_Usage_Value1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Usage_Value1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Usage_Value1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Usage_Value1, &ui_font_Number_Small, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button_Panel1 = lv_obj_create(ui_MainScreen);
lv_obj_set_width( ui_Button_Panel1, 240);
lv_obj_set_height( ui_Button_Panel1, 40);
lv_obj_set_x( ui_Button_Panel1, 0 );
lv_obj_set_y( ui_Button_Panel1, 140 );
lv_obj_set_align( ui_Button_Panel1, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Button_Panel1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(ui_Button_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Button_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Button_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonLeft1 = lv_button_create(ui_Button_Panel1);
lv_obj_set_width( ui_ButtonLeft1, lv_pct(25));
lv_obj_set_height( ui_ButtonLeft1, lv_pct(300));
lv_obj_set_y( ui_ButtonLeft1, 0 );
lv_obj_set_x( ui_ButtonLeft1, lv_pct(-44) );
lv_obj_set_align( ui_ButtonLeft1, LV_ALIGN_CENTER );
lv_obj_add_state( ui_ButtonLeft1, LV_STATE_USER_1 );     /// States
lv_obj_remove_flag( ui_ButtonLeft1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_image_src( ui_ButtonLeft1, &ui_img_2022142161, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_image_recolor(ui_ButtonLeft1, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonLeft1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_ButtonLeft1, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_ButtonLeft1, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_ButtonLeft1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_ButtonLeft1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_x(ui_ButtonLeft1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_y(ui_ButtonLeft1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( ui_ButtonLeft1, &ui_img_2022142161, LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_bg_image_recolor(ui_ButtonLeft1, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonLeft1, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_bg_image_src( ui_ButtonLeft1, &ui_img_732690875, LV_PART_MAIN | LV_STATE_USER_2 );
lv_obj_set_style_bg_image_recolor(ui_ButtonLeft1, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_2);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonLeft1, 255, LV_PART_MAIN| LV_STATE_USER_2);

ui_ButtonMidLeft1 = lv_button_create(ui_Button_Panel1);
lv_obj_set_width( ui_ButtonMidLeft1, lv_pct(25));
lv_obj_set_height( ui_ButtonMidLeft1, lv_pct(300));
lv_obj_set_y( ui_ButtonMidLeft1, 0 );
lv_obj_set_x( ui_ButtonMidLeft1, lv_pct(-15) );
lv_obj_set_align( ui_ButtonMidLeft1, LV_ALIGN_CENTER );
lv_obj_add_state( ui_ButtonMidLeft1, LV_STATE_USER_1 );     /// States
lv_obj_remove_flag( ui_ButtonMidLeft1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_image_src( ui_ButtonMidLeft1, &ui_img_2022142161, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_image_recolor(ui_ButtonMidLeft1, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonMidLeft1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_ButtonMidLeft1, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_ButtonMidLeft1, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_ButtonMidLeft1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_ButtonMidLeft1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_x(ui_ButtonMidLeft1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_y(ui_ButtonMidLeft1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( ui_ButtonMidLeft1, &ui_img_33364130, LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_bg_image_recolor(ui_ButtonMidLeft1, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonMidLeft1, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_bg_image_src( ui_ButtonMidLeft1, &ui_img_732690875, LV_PART_MAIN | LV_STATE_USER_2 );
lv_obj_set_style_bg_image_recolor(ui_ButtonMidLeft1, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_2);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonMidLeft1, 255, LV_PART_MAIN| LV_STATE_USER_2);

ui_ButtonMidRight1 = lv_button_create(ui_Button_Panel1);
lv_obj_set_width( ui_ButtonMidRight1, lv_pct(25));
lv_obj_set_height( ui_ButtonMidRight1, lv_pct(300));
lv_obj_set_y( ui_ButtonMidRight1, 0 );
lv_obj_set_x( ui_ButtonMidRight1, lv_pct(15) );
lv_obj_set_align( ui_ButtonMidRight1, LV_ALIGN_CENTER );
lv_obj_add_state( ui_ButtonMidRight1, LV_STATE_USER_2 );     /// States
lv_obj_remove_flag( ui_ButtonMidRight1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_image_src( ui_ButtonMidRight1, &ui_img_2022142161, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_image_recolor(ui_ButtonMidRight1, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonMidRight1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_ButtonMidRight1, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_ButtonMidRight1, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_ButtonMidRight1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_ButtonMidRight1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_x(ui_ButtonMidRight1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_y(ui_ButtonMidRight1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( ui_ButtonMidRight1, &ui_img_1713356312, LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_bg_image_recolor(ui_ButtonMidRight1, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonMidRight1, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_bg_image_src( ui_ButtonMidRight1, &ui_img_548664401, LV_PART_MAIN | LV_STATE_USER_2 );
lv_obj_set_style_bg_image_recolor(ui_ButtonMidRight1, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_2);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonMidRight1, 255, LV_PART_MAIN| LV_STATE_USER_2);
lv_obj_set_style_bg_image_src( ui_ButtonMidRight1, &ui_img_732690875, LV_PART_MAIN | LV_STATE_USER_3 );
lv_obj_set_style_bg_image_recolor(ui_ButtonMidRight1, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_3);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonMidRight1, 255, LV_PART_MAIN| LV_STATE_USER_3);
lv_obj_set_style_bg_image_src( ui_ButtonMidRight1, &ui_img_719203222, LV_PART_MAIN | LV_STATE_USER_4 );
lv_obj_set_style_bg_image_recolor(ui_ButtonMidRight1, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_4);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonMidRight1, 255, LV_PART_MAIN| LV_STATE_USER_4);

ui_ButtonRight1 = lv_button_create(ui_Button_Panel1);
lv_obj_set_width( ui_ButtonRight1, lv_pct(25));
lv_obj_set_height( ui_ButtonRight1, lv_pct(300));
lv_obj_set_y( ui_ButtonRight1, 0 );
lv_obj_set_x( ui_ButtonRight1, lv_pct(44) );
lv_obj_set_align( ui_ButtonRight1, LV_ALIGN_CENTER );
lv_obj_add_state( ui_ButtonRight1, LV_STATE_USER_2 );     /// States
lv_obj_remove_flag( ui_ButtonRight1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_image_src( ui_ButtonRight1, &ui_img_2022142161, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_image_recolor(ui_ButtonRight1, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonRight1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_ButtonRight1, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_ButtonRight1, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_ButtonRight1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_ButtonRight1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_x(ui_ButtonRight1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_y(ui_ButtonRight1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( ui_ButtonRight1, &ui_img_1546845897, LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_bg_image_recolor(ui_ButtonRight1, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonRight1, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_bg_image_src( ui_ButtonRight1, &ui_img_1759250347, LV_PART_MAIN | LV_STATE_USER_2 );
lv_obj_set_style_bg_image_recolor(ui_ButtonRight1, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_2);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonRight1, 255, LV_PART_MAIN| LV_STATE_USER_2);
lv_obj_set_style_bg_image_src( ui_ButtonRight1, &ui_img_732690875, LV_PART_MAIN | LV_STATE_USER_3 );
lv_obj_set_style_bg_image_recolor(ui_ButtonRight1, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_3);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonRight1, 255, LV_PART_MAIN| LV_STATE_USER_3);
lv_obj_set_style_bg_image_src( ui_ButtonRight1, &ui_img_719203222, LV_PART_MAIN | LV_STATE_USER_4 );
lv_obj_set_style_bg_image_recolor(ui_ButtonRight1, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_4);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonRight1, 255, LV_PART_MAIN| LV_STATE_USER_4);

ui_Header1 = lv_obj_create(ui_MainScreen);
lv_obj_set_height( ui_Header1, 50);
lv_obj_set_width( ui_Header1, lv_pct(100));
lv_obj_set_align( ui_Header1, LV_ALIGN_TOP_MID );
lv_obj_remove_flag( ui_Header1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Header1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Header1, lv_color_hex(0x14191E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Header1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Header1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Header_Battery1 = lv_label_create(ui_Header1);
lv_obj_set_width( ui_Header_Battery1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Header_Battery1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Header_Battery1, 0 );
lv_obj_set_y( ui_Header_Battery1, 6 );
lv_obj_set_align( ui_Header_Battery1, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Header_Battery1,"80%");
lv_obj_remove_flag( ui_Header_Battery1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_Header_Battery1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Header_Battery1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Roller_Topic1 = lv_roller_create(ui_Header1);
lv_roller_set_options( ui_Roller_Topic1, "Settings\nStrength\nFreq Cycle\nFrequency\nIntensity\nInterval Gap\nFilter\nModulate", LV_ROLLER_MODE_INFINITE );
lv_roller_set_selected( ui_Roller_Topic1, 1, LV_ANIM_OFF);
lv_obj_set_height( ui_Roller_Topic1, 55);
lv_obj_set_width( ui_Roller_Topic1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_Roller_Topic1, -60 );
lv_obj_set_y( ui_Roller_Topic1, 0 );
lv_obj_set_align( ui_Roller_Topic1, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Roller_Topic1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_obj_set_style_text_color(ui_Roller_Topic1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Roller_Topic1, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Roller_Topic1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Roller_Topic1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Roller_Topic1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Roller_Topic1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Roller_Topic1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Roller_Topic1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Roller_Topic1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_Roller_Topic1, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Roller_Topic1, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Roller_Topic1, LV_TEXT_ALIGN_CENTER, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Roller_Topic1, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Roller_Topic1, 0, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_Batt_Icon1 = lv_image_create(ui_Header1);
lv_image_set_src(ui_Batt_Icon1, &ui_img_battery_low_png);
lv_obj_set_width( ui_Batt_Icon1, 30);
lv_obj_set_height( ui_Batt_Icon1, 20);
lv_obj_set_x( ui_Batt_Icon1, 90 );
lv_obj_set_y( ui_Batt_Icon1, -8 );
lv_obj_set_align( ui_Batt_Icon1, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Batt_Icon1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_image_set_inner_align( ui_Batt_Icon1, LV_IMAGE_ALIGN_TILE );
lv_obj_set_style_bg_image_src( ui_Batt_Icon1, &ui_img_battery_low_png, LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_bg_image_opa(ui_Batt_Icon1, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_bg_image_src( ui_Batt_Icon1, &ui_img_battery_discharge_png, LV_PART_MAIN | LV_STATE_USER_2 );
lv_obj_set_style_bg_image_opa(ui_Batt_Icon1, 255, LV_PART_MAIN| LV_STATE_USER_2);
lv_obj_set_style_bg_image_src( ui_Batt_Icon1, &ui_img_battery_full_png, LV_PART_MAIN | LV_STATE_USER_3 );
lv_obj_set_style_bg_image_opa(ui_Batt_Icon1, 255, LV_PART_MAIN| LV_STATE_USER_3);
lv_obj_set_style_bg_image_src( ui_Batt_Icon1, &ui_img_battery_charging_png, LV_PART_MAIN | LV_STATE_USER_4 );
lv_obj_set_style_bg_image_opa(ui_Batt_Icon1, 255, LV_PART_MAIN| LV_STATE_USER_4);

ui_BT_Icon1 = lv_image_create(ui_Header1);
lv_image_set_src(ui_BT_Icon1, &ui_img_bluetooth_icon_png);
lv_obj_set_width( ui_BT_Icon1, 30);
lv_obj_set_height( ui_BT_Icon1, 30);
lv_obj_set_x( ui_BT_Icon1, 50 );
lv_obj_set_y( ui_BT_Icon1, -1 );
lv_obj_set_align( ui_BT_Icon1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BT_Icon1, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_remove_flag( ui_BT_Icon1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_image_set_inner_align( ui_BT_Icon1, LV_IMAGE_ALIGN_TILE );

lv_obj_add_event_cb(ui_Arc1, ui_event_Arc1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Ring1, ui_event_Ring1, LV_EVENT_ALL, NULL);

}

void ui_MainScreen_screen_destroy(void)
{
   if (ui_MainScreen) lv_obj_del(ui_MainScreen);

// NULL screen variables
ui_MainScreen= NULL;
ui_Arc_Group1= NULL;
ui_Arc1= NULL;
ui_Ring1= NULL;
ui_Value_Num_Bg1= NULL;
ui_Label_Value1= NULL;
ui_Value_Bg1= NULL;
ui_Freq_Text1= NULL;
ui_Freq_Value1= NULL;
ui_Usage_Text1= NULL;
ui_Usage_Value1= NULL;
ui_Button_Panel1= NULL;
ui_ButtonLeft1= NULL;
ui_ButtonMidLeft1= NULL;
ui_ButtonMidRight1= NULL;
ui_ButtonRight1= NULL;
ui_Header1= NULL;
ui_Header_Battery1= NULL;
ui_Roller_Topic1= NULL;
ui_Batt_Icon1= NULL;
ui_BT_Icon1= NULL;

}
