// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: ebf_final_va

#include "ui.h"

lv_obj_t *ui_SettingScreen = NULL;lv_obj_t *ui_Usage_Text2 = NULL;lv_obj_t *ui_Usage_Value2 = NULL;lv_obj_t *ui_Button_Panel4 = NULL;lv_obj_t *ui_ButtonLeft4 = NULL;lv_obj_t *ui_ButtonMidLeft4 = NULL;lv_obj_t *ui_ButtonMidRight4 = NULL;lv_obj_t *ui_ButtonRight4 = NULL;lv_obj_t *ui_Header4 = NULL;lv_obj_t *ui_Header_Battery4 = NULL;lv_obj_t *ui_Roller_Topic4 = NULL;lv_obj_t *ui_Batt_Icon4 = NULL;lv_obj_t *ui_BT_Icon4 = NULL;lv_obj_t *ui_Freq_Value5 = NULL;lv_obj_t *ui_Roller_Topic6 = NULL;lv_obj_t *ui_Freq_Text5 = NULL;
// event funtions

// build funtions

void ui_SettingScreen_screen_init(void)
{
ui_SettingScreen = lv_obj_create(NULL);
lv_obj_remove_flag( ui_SettingScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_style_bg_color(ui_SettingScreen, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SettingScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_SettingScreen, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT );

ui_Usage_Text2 = lv_label_create(ui_SettingScreen);
lv_obj_set_width( ui_Usage_Text2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Usage_Text2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Usage_Text2, -188 );
lv_obj_set_y( ui_Usage_Text2, 89 );
lv_obj_set_align( ui_Usage_Text2, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Usage_Text2,"Usage:");
lv_obj_add_flag( ui_Usage_Text2, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_remove_flag( ui_Usage_Text2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_Usage_Text2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Usage_Text2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Usage_Value2 = lv_label_create(ui_SettingScreen);
lv_obj_set_width( ui_Usage_Value2, 77);
lv_obj_set_height( ui_Usage_Value2, 25);
lv_obj_set_x( ui_Usage_Value2, -72 );
lv_obj_set_y( ui_Usage_Value2, 112 );
lv_obj_set_align( ui_Usage_Value2, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_Usage_Value2,LV_LABEL_LONG_CLIP);
lv_label_set_text(ui_Usage_Value2,"888H88m");
lv_obj_add_flag( ui_Usage_Value2, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_remove_flag( ui_Usage_Value2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_Usage_Value2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Usage_Value2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Usage_Value2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Usage_Value2, &ui_font_Number_Small, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button_Panel4 = lv_obj_create(ui_SettingScreen);
lv_obj_set_width( ui_Button_Panel4, 240);
lv_obj_set_height( ui_Button_Panel4, 40);
lv_obj_set_x( ui_Button_Panel4, 0 );
lv_obj_set_y( ui_Button_Panel4, 140 );
lv_obj_set_align( ui_Button_Panel4, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Button_Panel4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(ui_Button_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button_Panel4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Button_Panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Button_Panel4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonLeft4 = lv_button_create(ui_Button_Panel4);
lv_obj_set_width( ui_ButtonLeft4, lv_pct(25));
lv_obj_set_height( ui_ButtonLeft4, lv_pct(300));
lv_obj_set_y( ui_ButtonLeft4, 0 );
lv_obj_set_x( ui_ButtonLeft4, lv_pct(-44) );
lv_obj_set_align( ui_ButtonLeft4, LV_ALIGN_CENTER );
lv_obj_add_state( ui_ButtonLeft4, LV_STATE_USER_2 );     /// States
lv_obj_remove_flag( ui_ButtonLeft4, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_image_src( ui_ButtonLeft4, &ui_img_2022142161, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_image_recolor(ui_ButtonLeft4, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonLeft4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_ButtonLeft4, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_ButtonLeft4, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_ButtonLeft4, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_ButtonLeft4, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_x(ui_ButtonLeft4, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_y(ui_ButtonLeft4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( ui_ButtonLeft4, &ui_img_2022142161, LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_bg_image_recolor(ui_ButtonLeft4, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonLeft4, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_bg_image_src( ui_ButtonLeft4, &ui_img_732690875, LV_PART_MAIN | LV_STATE_USER_2 );
lv_obj_set_style_bg_image_recolor(ui_ButtonLeft4, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_2);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonLeft4, 255, LV_PART_MAIN| LV_STATE_USER_2);

ui_ButtonMidLeft4 = lv_button_create(ui_Button_Panel4);
lv_obj_set_width( ui_ButtonMidLeft4, lv_pct(25));
lv_obj_set_height( ui_ButtonMidLeft4, lv_pct(300));
lv_obj_set_y( ui_ButtonMidLeft4, 0 );
lv_obj_set_x( ui_ButtonMidLeft4, lv_pct(-15) );
lv_obj_set_align( ui_ButtonMidLeft4, LV_ALIGN_CENTER );
lv_obj_add_state( ui_ButtonMidLeft4, LV_STATE_USER_1 );     /// States
lv_obj_remove_flag( ui_ButtonMidLeft4, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_image_src( ui_ButtonMidLeft4, &ui_img_2022142161, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_image_recolor(ui_ButtonMidLeft4, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonMidLeft4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_ButtonMidLeft4, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_ButtonMidLeft4, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_ButtonMidLeft4, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_ButtonMidLeft4, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_x(ui_ButtonMidLeft4, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_y(ui_ButtonMidLeft4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( ui_ButtonMidLeft4, &ui_img_33364130, LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_bg_image_recolor(ui_ButtonMidLeft4, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonMidLeft4, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_bg_image_src( ui_ButtonMidLeft4, &ui_img_732690875, LV_PART_MAIN | LV_STATE_USER_2 );
lv_obj_set_style_bg_image_recolor(ui_ButtonMidLeft4, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_2);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonMidLeft4, 255, LV_PART_MAIN| LV_STATE_USER_2);

ui_ButtonMidRight4 = lv_button_create(ui_Button_Panel4);
lv_obj_set_width( ui_ButtonMidRight4, lv_pct(25));
lv_obj_set_height( ui_ButtonMidRight4, lv_pct(300));
lv_obj_set_y( ui_ButtonMidRight4, 0 );
lv_obj_set_x( ui_ButtonMidRight4, lv_pct(15) );
lv_obj_set_align( ui_ButtonMidRight4, LV_ALIGN_CENTER );
lv_obj_add_state( ui_ButtonMidRight4, LV_STATE_USER_2 );     /// States
lv_obj_remove_flag( ui_ButtonMidRight4, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_image_src( ui_ButtonMidRight4, &ui_img_2022142161, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_image_recolor(ui_ButtonMidRight4, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonMidRight4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_ButtonMidRight4, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_ButtonMidRight4, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_ButtonMidRight4, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_ButtonMidRight4, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_x(ui_ButtonMidRight4, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_y(ui_ButtonMidRight4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( ui_ButtonMidRight4, &ui_img_1713356312, LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_bg_image_recolor(ui_ButtonMidRight4, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonMidRight4, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_bg_image_src( ui_ButtonMidRight4, &ui_img_548664401, LV_PART_MAIN | LV_STATE_USER_2 );
lv_obj_set_style_bg_image_recolor(ui_ButtonMidRight4, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_2);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonMidRight4, 255, LV_PART_MAIN| LV_STATE_USER_2);
lv_obj_set_style_bg_image_src( ui_ButtonMidRight4, &ui_img_732690875, LV_PART_MAIN | LV_STATE_USER_3 );
lv_obj_set_style_bg_image_recolor(ui_ButtonMidRight4, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_3);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonMidRight4, 255, LV_PART_MAIN| LV_STATE_USER_3);
lv_obj_set_style_bg_image_src( ui_ButtonMidRight4, &ui_img_732690875, LV_PART_MAIN | LV_STATE_USER_4 );
lv_obj_set_style_bg_image_recolor(ui_ButtonMidRight4, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_4);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonMidRight4, 255, LV_PART_MAIN| LV_STATE_USER_4);

ui_ButtonRight4 = lv_button_create(ui_Button_Panel4);
lv_obj_set_width( ui_ButtonRight4, lv_pct(25));
lv_obj_set_height( ui_ButtonRight4, lv_pct(300));
lv_obj_set_y( ui_ButtonRight4, 0 );
lv_obj_set_x( ui_ButtonRight4, lv_pct(44) );
lv_obj_set_align( ui_ButtonRight4, LV_ALIGN_CENTER );
lv_obj_add_state( ui_ButtonRight4, LV_STATE_USER_2 );     /// States
lv_obj_remove_flag( ui_ButtonRight4, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_image_src( ui_ButtonRight4, &ui_img_2022142161, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_image_recolor(ui_ButtonRight4, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonRight4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_ButtonRight4, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_ButtonRight4, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_ButtonRight4, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_ButtonRight4, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_x(ui_ButtonRight4, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_y(ui_ButtonRight4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( ui_ButtonRight4, &ui_img_1546845897, LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_bg_image_recolor(ui_ButtonRight4, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonRight4, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_bg_image_src( ui_ButtonRight4, &ui_img_1759250347, LV_PART_MAIN | LV_STATE_USER_2 );
lv_obj_set_style_bg_image_recolor(ui_ButtonRight4, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_2);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonRight4, 255, LV_PART_MAIN| LV_STATE_USER_2);
lv_obj_set_style_bg_image_src( ui_ButtonRight4, &ui_img_732690875, LV_PART_MAIN | LV_STATE_USER_3 );
lv_obj_set_style_bg_image_recolor(ui_ButtonRight4, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_3);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonRight4, 255, LV_PART_MAIN| LV_STATE_USER_3);
lv_obj_set_style_bg_image_src( ui_ButtonRight4, &ui_img_719203222, LV_PART_MAIN | LV_STATE_USER_4 );
lv_obj_set_style_bg_image_recolor(ui_ButtonRight4, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_4);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonRight4, 255, LV_PART_MAIN| LV_STATE_USER_4);

ui_Header4 = lv_obj_create(ui_SettingScreen);
lv_obj_set_height( ui_Header4, 50);
lv_obj_set_width( ui_Header4, lv_pct(100));
lv_obj_set_align( ui_Header4, LV_ALIGN_TOP_MID );
lv_obj_remove_flag( ui_Header4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Header4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Header4, lv_color_hex(0x14191E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Header4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Header4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Header_Battery4 = lv_label_create(ui_Header4);
lv_obj_set_width( ui_Header_Battery4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Header_Battery4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Header_Battery4, 0 );
lv_obj_set_y( ui_Header_Battery4, 6 );
lv_obj_set_align( ui_Header_Battery4, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Header_Battery4,"80%");
lv_obj_remove_flag( ui_Header_Battery4, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_Header_Battery4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Header_Battery4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Roller_Topic4 = lv_roller_create(ui_Header4);
lv_roller_set_options( ui_Roller_Topic4, "Settings\nStrength\nFreq Cycle\nFrequency\nIntensity\nInterval Gap\nFilter\nModulate", LV_ROLLER_MODE_INFINITE );
lv_roller_set_selected( ui_Roller_Topic4, 8, LV_ANIM_OFF);
lv_obj_set_height( ui_Roller_Topic4, 55);
lv_obj_set_width( ui_Roller_Topic4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_Roller_Topic4, -60 );
lv_obj_set_y( ui_Roller_Topic4, 0 );
lv_obj_set_align( ui_Roller_Topic4, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Roller_Topic4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_obj_set_style_text_color(ui_Roller_Topic4, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Roller_Topic4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Roller_Topic4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Roller_Topic4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Roller_Topic4, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Roller_Topic4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Roller_Topic4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Roller_Topic4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Roller_Topic4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_Roller_Topic4, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Roller_Topic4, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Roller_Topic4, LV_TEXT_ALIGN_CENTER, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Roller_Topic4, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Roller_Topic4, 0, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_Batt_Icon4 = lv_image_create(ui_Header4);
lv_image_set_src(ui_Batt_Icon4, &ui_img_battery_low_png);
lv_obj_set_width( ui_Batt_Icon4, 30);
lv_obj_set_height( ui_Batt_Icon4, 20);
lv_obj_set_x( ui_Batt_Icon4, 90 );
lv_obj_set_y( ui_Batt_Icon4, -8 );
lv_obj_set_align( ui_Batt_Icon4, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Batt_Icon4, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_image_set_inner_align( ui_Batt_Icon4, LV_IMAGE_ALIGN_TILE );
lv_obj_set_style_bg_image_src( ui_Batt_Icon4, &ui_img_battery_low_png, LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_bg_image_opa(ui_Batt_Icon4, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_bg_image_src( ui_Batt_Icon4, &ui_img_battery_discharge_png, LV_PART_MAIN | LV_STATE_USER_2 );
lv_obj_set_style_bg_image_opa(ui_Batt_Icon4, 255, LV_PART_MAIN| LV_STATE_USER_2);
lv_obj_set_style_bg_image_src( ui_Batt_Icon4, &ui_img_battery_full_png, LV_PART_MAIN | LV_STATE_USER_3 );
lv_obj_set_style_bg_image_opa(ui_Batt_Icon4, 255, LV_PART_MAIN| LV_STATE_USER_3);
lv_obj_set_style_bg_image_src( ui_Batt_Icon4, &ui_img_battery_charging_png, LV_PART_MAIN | LV_STATE_USER_4 );
lv_obj_set_style_bg_image_opa(ui_Batt_Icon4, 255, LV_PART_MAIN| LV_STATE_USER_4);

ui_BT_Icon4 = lv_image_create(ui_Header4);
lv_image_set_src(ui_BT_Icon4, &ui_img_bluetooth_icon_png);
lv_obj_set_width( ui_BT_Icon4, 30);
lv_obj_set_height( ui_BT_Icon4, 30);
lv_obj_set_x( ui_BT_Icon4, 50 );
lv_obj_set_y( ui_BT_Icon4, -1 );
lv_obj_set_align( ui_BT_Icon4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BT_Icon4, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_remove_flag( ui_BT_Icon4, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_image_set_inner_align( ui_BT_Icon4, LV_IMAGE_ALIGN_TILE );

ui_Freq_Value5 = lv_label_create(ui_SettingScreen);
lv_obj_set_width( ui_Freq_Value5, 77);
lv_obj_set_height( ui_Freq_Value5, 25);
lv_obj_set_x( ui_Freq_Value5, 49 );
lv_obj_set_y( ui_Freq_Value5, 17 );
lv_obj_set_align( ui_Freq_Value5, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_Freq_Value5,LV_LABEL_LONG_CLIP);
lv_label_set_text(ui_Freq_Value5,"30s");
lv_obj_remove_flag( ui_Freq_Value5, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_Freq_Value5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Freq_Value5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Freq_Value5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Freq_Value5, &ui_font_Number_Small, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Roller_Topic6 = lv_roller_create(ui_SettingScreen);
lv_roller_set_options( ui_Roller_Topic6, "Auto Shutdown Timer\nBrightness\nTotal Therapy Time", LV_ROLLER_MODE_INFINITE );
lv_obj_set_height( ui_Roller_Topic6, 47);
lv_obj_set_width( ui_Roller_Topic6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_Roller_Topic6, -8 );
lv_obj_set_y( ui_Roller_Topic6, -31 );
lv_obj_set_align( ui_Roller_Topic6, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Roller_Topic6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_obj_set_style_text_color(ui_Roller_Topic6, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Roller_Topic6, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Roller_Topic6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Roller_Topic6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Roller_Topic6, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Roller_Topic6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Roller_Topic6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Roller_Topic6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Roller_Topic6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_Roller_Topic6, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Roller_Topic6, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Roller_Topic6, LV_TEXT_ALIGN_CENTER, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Roller_Topic6, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Roller_Topic6, 0, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_Freq_Text5 = lv_label_create(ui_SettingScreen);
lv_obj_set_width( ui_Freq_Text5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Freq_Text5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Freq_Text5, -87 );
lv_obj_set_y( ui_Freq_Text5, 103 );
lv_obj_set_align( ui_Freq_Text5, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Freq_Text5,"EBF v0.1.0");
lv_obj_remove_flag( ui_Freq_Text5, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_Freq_Text5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Freq_Text5, 100, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_SettingScreen_screen_destroy(void)
{
   if (ui_SettingScreen) lv_obj_del(ui_SettingScreen);

// NULL screen variables
ui_SettingScreen= NULL;
ui_Usage_Text2= NULL;
ui_Usage_Value2= NULL;
ui_Button_Panel4= NULL;
ui_ButtonLeft4= NULL;
ui_ButtonMidLeft4= NULL;
ui_ButtonMidRight4= NULL;
ui_ButtonRight4= NULL;
ui_Header4= NULL;
ui_Header_Battery4= NULL;
ui_Roller_Topic4= NULL;
ui_Batt_Icon4= NULL;
ui_BT_Icon4= NULL;
ui_Freq_Value5= NULL;
ui_Roller_Topic6= NULL;
ui_Freq_Text5= NULL;

}
