// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: ebf_final_va

#ifndef UI_SETTINGSCREEN_H
#define UI_SETTINGSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif


// SCREEN: ui_SettingScreen
extern void ui_SettingScreen_screen_init(void);
extern void ui_SettingScreen_screen_destroy(void);
extern lv_obj_t *ui_SettingScreen;
extern lv_obj_t *ui_Usage_Text2;
extern lv_obj_t *ui_Usage_Value2;
extern lv_obj_t *ui_Button_Panel4;
extern lv_obj_t *ui_ButtonLeft4;
extern lv_obj_t *ui_ButtonMidLeft4;
extern lv_obj_t *ui_ButtonMidRight4;
extern lv_obj_t *ui_ButtonRight4;
extern lv_obj_t *ui_Header4;
extern lv_obj_t *ui_Header_Battery4;
extern lv_obj_t *ui_Roller_Topic4;
extern lv_obj_t *ui_Batt_Icon4;
extern lv_obj_t *ui_BT_Icon4;
extern lv_obj_t *ui_Freq_Value5;
extern lv_obj_t *ui_Roller_Topic6;
extern lv_obj_t *ui_Freq_Text5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

