// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: ebf_final_va

#include "ui.h"

lv_obj_t *ui_TherapyScreen = NULL;lv_obj_t *ui_Header2 = NULL;lv_obj_t *ui_Header_Battery2 = NULL;lv_obj_t *ui_Roller_Topic2 = NULL;lv_obj_t *ui_Batt_Icon2 = NULL;lv_obj_t *ui_BT_Icon2 = NULL;lv_obj_t *ui_Start_Group2 = NULL;lv_obj_t *ui_Start_Bg2 = NULL;lv_obj_t *ui_Start_Num_Bg2 = NULL;lv_obj_t *ui_Label_Start2 = NULL;lv_obj_t *ui_Freq_Text2 = NULL;lv_obj_t *ui_Freq_Value2 = NULL;lv_obj_t *ui_Button_Panel2 = NULL;lv_obj_t *ui_ButtonLeft2 = NULL;lv_obj_t *ui_ButtonMidLeft2 = NULL;lv_obj_t *ui_ButtonMidRight2 = NULL;lv_obj_t *ui_ButtonRight2 = NULL;lv_obj_t *ui_Present_Group1 = NULL;lv_obj_t *ui_Present_Bg1 = NULL;lv_obj_t *ui_Present_Num_Bg1 = NULL;lv_obj_t *ui_Label_Present1 = NULL;lv_obj_t *ui_Speed_Group = NULL;lv_obj_t *ui_Speed_Bg = NULL;lv_obj_t *ui_Speed_Num_Bg = NULL;lv_obj_t *ui_Label_Speed = NULL;
// event funtions

// build funtions

void ui_TherapyScreen_screen_init(void)
{
ui_TherapyScreen = lv_obj_create(NULL);
lv_obj_remove_flag( ui_TherapyScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_style_bg_color(ui_TherapyScreen, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TherapyScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_TherapyScreen, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT );

ui_Header2 = lv_obj_create(ui_TherapyScreen);
lv_obj_set_height( ui_Header2, 50);
lv_obj_set_width( ui_Header2, lv_pct(100));
lv_obj_set_align( ui_Header2, LV_ALIGN_TOP_MID );
lv_obj_remove_flag( ui_Header2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Header2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Header2, lv_color_hex(0x14191E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Header2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Header2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Header_Battery2 = lv_label_create(ui_Header2);
lv_obj_set_width( ui_Header_Battery2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Header_Battery2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Header_Battery2, 0 );
lv_obj_set_y( ui_Header_Battery2, 6 );
lv_obj_set_align( ui_Header_Battery2, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Header_Battery2,"80%");
lv_obj_remove_flag( ui_Header_Battery2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_Header_Battery2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Header_Battery2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Roller_Topic2 = lv_roller_create(ui_Header2);
lv_roller_set_options( ui_Roller_Topic2, "Settings\nStrength\nFreq Cycle\nFrequency\nIntensity\nInterval Gap\nFilter\nModulate", LV_ROLLER_MODE_NORMAL );
lv_roller_set_selected( ui_Roller_Topic2, 1, LV_ANIM_OFF);
lv_obj_set_height( ui_Roller_Topic2, 55);
lv_obj_set_width( ui_Roller_Topic2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_Roller_Topic2, -60 );
lv_obj_set_y( ui_Roller_Topic2, 0 );
lv_obj_set_align( ui_Roller_Topic2, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Roller_Topic2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_obj_set_style_text_align(ui_Roller_Topic2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Roller_Topic2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Roller_Topic2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Roller_Topic2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Roller_Topic2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_Roller_Topic2, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Roller_Topic2, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Roller_Topic2, LV_TEXT_ALIGN_CENTER, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Roller_Topic2, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Roller_Topic2, 0, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_Batt_Icon2 = lv_image_create(ui_Header2);
lv_image_set_src(ui_Batt_Icon2, &ui_img_battery_low_png);
lv_obj_set_width( ui_Batt_Icon2, 30);
lv_obj_set_height( ui_Batt_Icon2, 20);
lv_obj_set_x( ui_Batt_Icon2, 90 );
lv_obj_set_y( ui_Batt_Icon2, -8 );
lv_obj_set_align( ui_Batt_Icon2, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Batt_Icon2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_image_set_inner_align( ui_Batt_Icon2, LV_IMAGE_ALIGN_TILE );
lv_obj_set_style_bg_image_src( ui_Batt_Icon2, &ui_img_battery_low_png, LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_bg_image_opa(ui_Batt_Icon2, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_bg_image_src( ui_Batt_Icon2, &ui_img_battery_discharge_png, LV_PART_MAIN | LV_STATE_USER_2 );
lv_obj_set_style_bg_image_opa(ui_Batt_Icon2, 255, LV_PART_MAIN| LV_STATE_USER_2);
lv_obj_set_style_bg_image_src( ui_Batt_Icon2, &ui_img_battery_full_png, LV_PART_MAIN | LV_STATE_USER_3 );
lv_obj_set_style_bg_image_opa(ui_Batt_Icon2, 255, LV_PART_MAIN| LV_STATE_USER_3);
lv_obj_set_style_bg_image_src( ui_Batt_Icon2, &ui_img_battery_charging_png, LV_PART_MAIN | LV_STATE_USER_4 );
lv_obj_set_style_bg_image_opa(ui_Batt_Icon2, 255, LV_PART_MAIN| LV_STATE_USER_4);

ui_BT_Icon2 = lv_image_create(ui_Header2);
lv_image_set_src(ui_BT_Icon2, &ui_img_bluetooth_icon_png);
lv_obj_set_width( ui_BT_Icon2, 30);
lv_obj_set_height( ui_BT_Icon2, 30);
lv_obj_set_x( ui_BT_Icon2, 50 );
lv_obj_set_y( ui_BT_Icon2, -1 );
lv_obj_set_align( ui_BT_Icon2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BT_Icon2, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_remove_flag( ui_BT_Icon2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_image_set_inner_align( ui_BT_Icon2, LV_IMAGE_ALIGN_TILE );

ui_Start_Group2 = lv_obj_create(ui_TherapyScreen);
lv_obj_set_width( ui_Start_Group2, 120);
lv_obj_set_height( ui_Start_Group2, 140);
lv_obj_set_x( ui_Start_Group2, -65 );
lv_obj_set_y( ui_Start_Group2, -54 );
lv_obj_set_align( ui_Start_Group2, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Start_Group2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(ui_Start_Group2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Start_Group2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Start_Group2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Start_Bg2 = lv_obj_create(ui_Start_Group2);
lv_obj_set_width( ui_Start_Bg2, 100);
lv_obj_set_height( ui_Start_Bg2, 100);
lv_obj_set_align( ui_Start_Bg2, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Start_Bg2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_Start_Bg2, 280, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Start_Bg2, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Start_Bg2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Start_Bg2, lv_color_hex(0x3C414B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_Start_Bg2, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Start_Bg2, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Start_Bg2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Start_Bg2, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Start_Bg2, lv_color_hex(0x050A0F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Start_Bg2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_Start_Bg2, 40, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Start_Bg2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_x(ui_Start_Bg2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_y(ui_Start_Bg2, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Start_Num_Bg2 = lv_obj_create(ui_Start_Bg2);
lv_obj_set_width( ui_Start_Num_Bg2, 80);
lv_obj_set_height( ui_Start_Num_Bg2, 80);
lv_obj_set_align( ui_Start_Num_Bg2, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Start_Num_Bg2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_Start_Num_Bg2, 200, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Start_Num_Bg2, lv_color_hex(0x0C191E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Start_Num_Bg2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Start_Num_Bg2, lv_color_hex(0x191C26), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_Start_Num_Bg2, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Start_Num_Bg2, lv_color_hex(0x5A646E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Start_Num_Bg2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Start2 = lv_label_create(ui_Start_Num_Bg2);
lv_obj_set_width( ui_Label_Start2, 60);
lv_obj_set_height( ui_Label_Start2, 33);
lv_obj_set_x( ui_Label_Start2, 5 );
lv_obj_set_y( ui_Label_Start2, 0 );
lv_obj_set_align( ui_Label_Start2, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_Label_Start2,LV_LABEL_LONG_CLIP);
lv_label_set_text(ui_Label_Start2,"888");
lv_obj_remove_flag( ui_Label_Start2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_Label_Start2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Start2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_Start2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Start2, &ui_font_Number_Medium, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Freq_Text2 = lv_label_create(ui_TherapyScreen);
lv_obj_set_width( ui_Freq_Text2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Freq_Text2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Freq_Text2, -198 );
lv_obj_set_y( ui_Freq_Text2, 89 );
lv_obj_set_align( ui_Freq_Text2, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Freq_Text2,"Freq:");
lv_obj_remove_flag( ui_Freq_Text2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_Freq_Text2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Freq_Text2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Freq_Value2 = lv_label_create(ui_TherapyScreen);
lv_obj_set_width( ui_Freq_Value2, 77);
lv_obj_set_height( ui_Freq_Value2, 25);
lv_obj_set_x( ui_Freq_Value2, -72 );
lv_obj_set_y( ui_Freq_Value2, 112 );
lv_obj_set_align( ui_Freq_Value2, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_Freq_Value2,LV_LABEL_LONG_CLIP);
lv_label_set_text(ui_Freq_Value2,"888Hz");
lv_obj_remove_flag( ui_Freq_Value2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_Freq_Value2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Freq_Value2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Freq_Value2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Freq_Value2, &ui_font_Number_Small, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button_Panel2 = lv_obj_create(ui_TherapyScreen);
lv_obj_set_width( ui_Button_Panel2, 240);
lv_obj_set_height( ui_Button_Panel2, 40);
lv_obj_set_x( ui_Button_Panel2, 0 );
lv_obj_set_y( ui_Button_Panel2, 140 );
lv_obj_set_align( ui_Button_Panel2, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Button_Panel2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(ui_Button_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button_Panel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Button_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Button_Panel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonLeft2 = lv_button_create(ui_Button_Panel2);
lv_obj_set_width( ui_ButtonLeft2, lv_pct(25));
lv_obj_set_height( ui_ButtonLeft2, lv_pct(300));
lv_obj_set_y( ui_ButtonLeft2, 0 );
lv_obj_set_x( ui_ButtonLeft2, lv_pct(-44) );
lv_obj_set_align( ui_ButtonLeft2, LV_ALIGN_CENTER );
lv_obj_add_state( ui_ButtonLeft2, LV_STATE_USER_1 );     /// States
lv_obj_remove_flag( ui_ButtonLeft2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_image_src( ui_ButtonLeft2, &ui_img_2022142161, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_image_recolor(ui_ButtonLeft2, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonLeft2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_ButtonLeft2, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_ButtonLeft2, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_ButtonLeft2, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_ButtonLeft2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_x(ui_ButtonLeft2, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_y(ui_ButtonLeft2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( ui_ButtonLeft2, &ui_img_2022142161, LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_bg_image_recolor(ui_ButtonLeft2, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonLeft2, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_bg_image_src( ui_ButtonLeft2, &ui_img_732690875, LV_PART_MAIN | LV_STATE_USER_2 );
lv_obj_set_style_bg_image_recolor(ui_ButtonLeft2, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_2);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonLeft2, 255, LV_PART_MAIN| LV_STATE_USER_2);

ui_ButtonMidLeft2 = lv_button_create(ui_Button_Panel2);
lv_obj_set_width( ui_ButtonMidLeft2, lv_pct(25));
lv_obj_set_height( ui_ButtonMidLeft2, lv_pct(300));
lv_obj_set_y( ui_ButtonMidLeft2, 0 );
lv_obj_set_x( ui_ButtonMidLeft2, lv_pct(-15) );
lv_obj_set_align( ui_ButtonMidLeft2, LV_ALIGN_CENTER );
lv_obj_add_state( ui_ButtonMidLeft2, LV_STATE_USER_1 );     /// States
lv_obj_remove_flag( ui_ButtonMidLeft2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_image_src( ui_ButtonMidLeft2, &ui_img_2022142161, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_image_recolor(ui_ButtonMidLeft2, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonMidLeft2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_ButtonMidLeft2, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_ButtonMidLeft2, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_ButtonMidLeft2, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_ButtonMidLeft2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_x(ui_ButtonMidLeft2, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_y(ui_ButtonMidLeft2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( ui_ButtonMidLeft2, &ui_img_33364130, LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_bg_image_recolor(ui_ButtonMidLeft2, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonMidLeft2, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_bg_image_src( ui_ButtonMidLeft2, &ui_img_732690875, LV_PART_MAIN | LV_STATE_USER_2 );
lv_obj_set_style_bg_image_recolor(ui_ButtonMidLeft2, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_2);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonMidLeft2, 255, LV_PART_MAIN| LV_STATE_USER_2);

ui_ButtonMidRight2 = lv_button_create(ui_Button_Panel2);
lv_obj_set_width( ui_ButtonMidRight2, lv_pct(25));
lv_obj_set_height( ui_ButtonMidRight2, lv_pct(300));
lv_obj_set_y( ui_ButtonMidRight2, 0 );
lv_obj_set_x( ui_ButtonMidRight2, lv_pct(15) );
lv_obj_set_align( ui_ButtonMidRight2, LV_ALIGN_CENTER );
lv_obj_add_state( ui_ButtonMidRight2, LV_STATE_USER_1 );     /// States
lv_obj_remove_flag( ui_ButtonMidRight2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_image_src( ui_ButtonMidRight2, &ui_img_2022142161, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_image_recolor(ui_ButtonMidRight2, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonMidRight2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_ButtonMidRight2, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_ButtonMidRight2, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_ButtonMidRight2, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_ButtonMidRight2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_x(ui_ButtonMidRight2, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_y(ui_ButtonMidRight2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( ui_ButtonMidRight2, &ui_img_1713356312, LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_bg_image_recolor(ui_ButtonMidRight2, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonMidRight2, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_bg_image_src( ui_ButtonMidRight2, &ui_img_548664401, LV_PART_MAIN | LV_STATE_USER_2 );
lv_obj_set_style_bg_image_recolor(ui_ButtonMidRight2, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_2);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonMidRight2, 255, LV_PART_MAIN| LV_STATE_USER_2);
lv_obj_set_style_bg_image_src( ui_ButtonMidRight2, &ui_img_732690875, LV_PART_MAIN | LV_STATE_USER_3 );
lv_obj_set_style_bg_image_recolor(ui_ButtonMidRight2, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_3);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonMidRight2, 255, LV_PART_MAIN| LV_STATE_USER_3);
lv_obj_set_style_bg_image_src( ui_ButtonMidRight2, &ui_img_732690875, LV_PART_MAIN | LV_STATE_USER_4 );
lv_obj_set_style_bg_image_recolor(ui_ButtonMidRight2, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_4);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonMidRight2, 255, LV_PART_MAIN| LV_STATE_USER_4);

ui_ButtonRight2 = lv_button_create(ui_Button_Panel2);
lv_obj_set_width( ui_ButtonRight2, lv_pct(25));
lv_obj_set_height( ui_ButtonRight2, lv_pct(300));
lv_obj_set_y( ui_ButtonRight2, 0 );
lv_obj_set_x( ui_ButtonRight2, lv_pct(44) );
lv_obj_set_align( ui_ButtonRight2, LV_ALIGN_CENTER );
lv_obj_add_state( ui_ButtonRight2, LV_STATE_USER_1 );     /// States
lv_obj_remove_flag( ui_ButtonRight2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_image_src( ui_ButtonRight2, &ui_img_2022142161, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_image_recolor(ui_ButtonRight2, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonRight2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_ButtonRight2, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_ButtonRight2, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_ButtonRight2, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_ButtonRight2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_x(ui_ButtonRight2, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_y(ui_ButtonRight2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( ui_ButtonRight2, &ui_img_1546845897, LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_bg_image_recolor(ui_ButtonRight2, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonRight2, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_bg_image_src( ui_ButtonRight2, &ui_img_1759250347, LV_PART_MAIN | LV_STATE_USER_2 );
lv_obj_set_style_bg_image_recolor(ui_ButtonRight2, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_2);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonRight2, 255, LV_PART_MAIN| LV_STATE_USER_2);
lv_obj_set_style_bg_image_src( ui_ButtonRight2, &ui_img_732690875, LV_PART_MAIN | LV_STATE_USER_3 );
lv_obj_set_style_bg_image_recolor(ui_ButtonRight2, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_3);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonRight2, 255, LV_PART_MAIN| LV_STATE_USER_3);
lv_obj_set_style_bg_image_src( ui_ButtonRight2, &ui_img_719203222, LV_PART_MAIN | LV_STATE_USER_4 );
lv_obj_set_style_bg_image_recolor(ui_ButtonRight2, lv_color_hex(0x14191E), LV_PART_MAIN| LV_STATE_USER_4);
lv_obj_set_style_bg_image_recolor_opa(ui_ButtonRight2, 255, LV_PART_MAIN| LV_STATE_USER_4);

ui_Present_Group1 = lv_obj_create(ui_TherapyScreen);
lv_obj_set_width( ui_Present_Group1, 120);
lv_obj_set_height( ui_Present_Group1, 140);
lv_obj_set_x( ui_Present_Group1, -65 );
lv_obj_set_y( ui_Present_Group1, 55 );
lv_obj_set_align( ui_Present_Group1, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Present_Group1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(ui_Present_Group1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Present_Group1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Present_Group1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Present_Bg1 = lv_obj_create(ui_Present_Group1);
lv_obj_set_width( ui_Present_Bg1, 100);
lv_obj_set_height( ui_Present_Bg1, 100);
lv_obj_set_align( ui_Present_Bg1, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Present_Bg1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_Present_Bg1, 280, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Present_Bg1, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Present_Bg1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Present_Bg1, lv_color_hex(0x3C414B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_Present_Bg1, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Present_Bg1, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Present_Bg1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Present_Bg1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Present_Bg1, lv_color_hex(0x050A0F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Present_Bg1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_Present_Bg1, 40, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Present_Bg1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_x(ui_Present_Bg1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_y(ui_Present_Bg1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Present_Num_Bg1 = lv_obj_create(ui_Present_Bg1);
lv_obj_set_width( ui_Present_Num_Bg1, 80);
lv_obj_set_height( ui_Present_Num_Bg1, 80);
lv_obj_set_align( ui_Present_Num_Bg1, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Present_Num_Bg1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_Present_Num_Bg1, 200, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Present_Num_Bg1, lv_color_hex(0x0C191E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Present_Num_Bg1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Present_Num_Bg1, lv_color_hex(0x191C26), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_Present_Num_Bg1, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Present_Num_Bg1, lv_color_hex(0x5A646E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Present_Num_Bg1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Present1 = lv_label_create(ui_Present_Num_Bg1);
lv_obj_set_width( ui_Label_Present1, 60);
lv_obj_set_height( ui_Label_Present1, 33);
lv_obj_set_x( ui_Label_Present1, 5 );
lv_obj_set_y( ui_Label_Present1, 0 );
lv_obj_set_align( ui_Label_Present1, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_Label_Present1,LV_LABEL_LONG_CLIP);
lv_label_set_text(ui_Label_Present1,"888");
lv_obj_remove_flag( ui_Label_Present1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_Label_Present1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Present1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_Present1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Present1, &ui_font_Number_Medium, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Speed_Group = lv_obj_create(ui_TherapyScreen);
lv_obj_set_width( ui_Speed_Group, 120);
lv_obj_set_height( ui_Speed_Group, 140);
lv_obj_set_x( ui_Speed_Group, 65 );
lv_obj_set_y( ui_Speed_Group, -54 );
lv_obj_set_align( ui_Speed_Group, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Speed_Group, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(ui_Speed_Group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Speed_Group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Speed_Group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Speed_Bg = lv_obj_create(ui_Speed_Group);
lv_obj_set_width( ui_Speed_Bg, 100);
lv_obj_set_height( ui_Speed_Bg, 100);
lv_obj_set_align( ui_Speed_Bg, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Speed_Bg, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_Speed_Bg, 280, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Speed_Bg, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Speed_Bg, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Speed_Bg, lv_color_hex(0x3C414B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_Speed_Bg, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Speed_Bg, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Speed_Bg, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Speed_Bg, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Speed_Bg, lv_color_hex(0x050A0F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Speed_Bg, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_Speed_Bg, 40, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Speed_Bg, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_x(ui_Speed_Bg, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_y(ui_Speed_Bg, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Speed_Num_Bg = lv_obj_create(ui_Speed_Bg);
lv_obj_set_width( ui_Speed_Num_Bg, 80);
lv_obj_set_height( ui_Speed_Num_Bg, 80);
lv_obj_set_align( ui_Speed_Num_Bg, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Speed_Num_Bg, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_Speed_Num_Bg, 200, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Speed_Num_Bg, lv_color_hex(0x0C191E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Speed_Num_Bg, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Speed_Num_Bg, lv_color_hex(0x191C26), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_Speed_Num_Bg, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Speed_Num_Bg, lv_color_hex(0x5A646E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Speed_Num_Bg, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Speed = lv_label_create(ui_Speed_Num_Bg);
lv_obj_set_width( ui_Label_Speed, 60);
lv_obj_set_height( ui_Label_Speed, 33);
lv_obj_set_x( ui_Label_Speed, 5 );
lv_obj_set_y( ui_Label_Speed, 0 );
lv_obj_set_align( ui_Label_Speed, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_Label_Speed,LV_LABEL_LONG_CLIP);
lv_label_set_text(ui_Label_Speed,"888");
lv_obj_remove_flag( ui_Label_Speed, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_Label_Speed, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Speed, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_Speed, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Speed, &ui_font_Number_Medium, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_TherapyScreen_screen_destroy(void)
{
   if (ui_TherapyScreen) lv_obj_del(ui_TherapyScreen);

// NULL screen variables
ui_TherapyScreen= NULL;
ui_Header2= NULL;
ui_Header_Battery2= NULL;
ui_Roller_Topic2= NULL;
ui_Batt_Icon2= NULL;
ui_BT_Icon2= NULL;
ui_Start_Group2= NULL;
ui_Start_Bg2= NULL;
ui_Start_Num_Bg2= NULL;
ui_Label_Start2= NULL;
ui_Freq_Text2= NULL;
ui_Freq_Value2= NULL;
ui_Button_Panel2= NULL;
ui_ButtonLeft2= NULL;
ui_ButtonMidLeft2= NULL;
ui_ButtonMidRight2= NULL;
ui_ButtonRight2= NULL;
ui_Present_Group1= NULL;
ui_Present_Bg1= NULL;
ui_Present_Num_Bg1= NULL;
ui_Label_Present1= NULL;
ui_Speed_Group= NULL;
ui_Speed_Bg= NULL;
ui_Speed_Num_Bg= NULL;
ui_Label_Speed= NULL;

}
