// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: ebf_final_va

#ifndef UI_THERAPYSCREEN_H
#define UI_THERAPYSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif


// SCREEN: ui_TherapyScreen
extern void ui_TherapyScreen_screen_init(void);
extern void ui_TherapyScreen_screen_destroy(void);
extern lv_obj_t *ui_TherapyScreen;
extern lv_obj_t *ui_Header2;
extern lv_obj_t *ui_Header_Battery2;
extern lv_obj_t *ui_Roller_Topic2;
extern lv_obj_t *ui_Batt_Icon2;
extern lv_obj_t *ui_BT_Icon2;
extern lv_obj_t *ui_Start_Group2;
extern lv_obj_t *ui_Start_Bg2;
extern lv_obj_t *ui_Start_Num_Bg2;
extern lv_obj_t *ui_Label_Start2;
extern lv_obj_t *ui_Freq_Text2;
extern lv_obj_t *ui_Freq_Value2;
extern lv_obj_t *ui_Button_Panel2;
extern lv_obj_t *ui_ButtonLeft2;
extern lv_obj_t *ui_ButtonMidLeft2;
extern lv_obj_t *ui_ButtonMidRight2;
extern lv_obj_t *ui_ButtonRight2;
extern lv_obj_t *ui_Present_Group1;
extern lv_obj_t *ui_Present_Bg1;
extern lv_obj_t *ui_Present_Num_Bg1;
extern lv_obj_t *ui_Label_Present1;
extern lv_obj_t *ui_Speed_Group;
extern lv_obj_t *ui_Speed_Bg;
extern lv_obj_t *ui_Speed_Num_Bg;
extern lv_obj_t *ui_Label_Speed;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

